### PR TITLE
Implement simple conditional assembly support.

### PR DESCRIPTION
**Pull request by pgregory**
Very rudimentary conditional assembly implementation just to suit my very specific needs. 

Introduces 3 new assembly commands, if, else, endif. Cannot be nested. The if just checks the value of a standard parameter value using the readily available getValue function, so can be used with EQU statements for example. If the value is 0, doesn't include the code in between the if and then endif, if non-zero, it does. The else just swaps the condition state.

i.e.

DEBUG: EQU 0

    if DEBUG
push hl
ld h, 16
ld l, 0
call print_Hex16
pop hl
    endif

### CODE REVIEW

**Comment by envenomator** [comment]
That is looking pretty complete already.
Is there a specific reason for the 'inConditionalSection' global variable to be declared as int? I'd rather set it to bool to promote readability.
Have you tested with inserted comments after the if/else/endif statements?

**Comment by pgregory** [comment]
The reason for the int is that 0 is outside any conditional section, 1 is in the negative section, and 2 the positive section, allowing differentiation between generating code in the if or else section vs generating code outside of any conditional statements. I did it that way specifically to allow more direct control over where it's valid to add an else or endif command.

I have tested with comments...

```
  if DEBUG
; Print keycode for identification
  push af
  ld l, a
  ld h, 0
  call home_cursor
  call print_Hex16
  pop af
  endif
```

**Comment by pgregory** [comment]
Just in case you meant inline, this works too...

	if DEBUG  ; Print keycode for identification
    push af
	ld l, a
	ld h, 0
	call home_cursor
	call print_Hex16
    pop af
	endif

**Comment by envenomator** [comment]
Ok; clear; thnx. 
I meant commenting like
if DEBUG ; some comment
<code>
else ; something else

**Comment by pgregory** [comment]
if USE_SPRITES ; use sprite mode
	call move_sprite			; Move sprite into position
	call next_frame_sprite		; Animate sprite frame
	else ; Use bitmap mode
	call clear_invader_bmp
	call draw_invader
	endif ; end sprite/bitmap check

**Comment by envenomator** [comment]
I'll pull this in a few days and output a new release, together with the other enhancements.
Thanks!

**Comment by envenomator** [comment]
I'm making some changes:
- To detect a missing 'endif' directive at the end of each file
- To detect a missing 'if' directive
- Reset the state variable 'inConditionalSection' to 0 at pass start

**Pull request merged**
