### PR TITLE
Accept RST.LIS as a valid instruction

### PR DESCRIPTION
**Pull request by dsnopek**
Possibly fixes issue #18

My program at least assembles! I haven't had a chance to test it, though (I'm converting from spasm-ng and not quite there yet :-))

### CODE REVIEW

**Comment by envenomator** [comment]
This is a weird one. The ez80 CPU manual doesn't state RST.LIS as an acceptable ADL suffix in ADL==1. However... their own ZDS assembler doesn't throw an error using it in ADL==1, still producing suffix 0x49. (See page 29/30 from the ez80CPU datasheet, and also page 326/327 - http://www.zilog.com/docs/um0077.pdf). 
I'll create a support case at Zilog to have them clarify this.

Capture

**Comment by dsnopek** [comment]
Thanks! I'm looking forward to hearing what Zilog has to say about it. :-)

A couple of thoughts in the meantime:

1. Since the processor can switch in and out of ADL mode at any time (via `CALL.LIS` to leave ADL mode in the subroutine, or `CALL.SIL` to enter ADL mode in the subroutine), and a single program could contain different subroutines for both ADL and non-ADL mode, the assembler probably should always allow all instructions even when it's "assuming" a particular mode. (Or, maybe have a way to tell the assembler not to assume anything?)
2. `RST` is actually quite similar to `CALL`, both in that it jumps to a subroutine and returns via `RET`, but also that you can use it to change the ADL mode. So, if the logic of my first point holds for `CALL`, then I think it makes sense to allow all modes for `RST` at all times too?

Anyway, I'm still very new to ez80 assembly, so my thoughts may not be totally coherent :-)

**Comment by envenomator** [comment]
Hi,

Regarding your first point; the assembler keeps track of ADL mode at each instruction, where you as a programmer set the ASSUME to allow the assembler using suffixes according to your specific mode needs. If your needs change within functions, that is easily done using ASSUME.

Regarding CALL instructions changing the mode; this is always by intent of the programmer writing the assembly. In mixed mode settings, each routine should be the correct ASSUME sequence anyway and the appropriate CALL suffixes will need to be given to enter these (see also appnotes http://www.zilog.com/docs/appnotes/an0339.pdf)

As I implement the design specs of the ez80 into the ez80assembler, I need to keep a reference of the specification to guard against potential side-effects of instructions. The ez80 datasheet is my primary reference, though sometimes it isn't very clear. This is not the first time I'm asking Zilog about their datasheet ;-) Will keep you posted when I hear back from them; this usually takes about a week or two

**Comment by envenomator** [comment]
Fixed in v0.98

**Pull request closed without merging**
