### PR TITLE
Update to build cross-platform

### PR DESCRIPTION
**Pull request by rprouse**
- Updates to build with Make on Windows and *nix systems
- Automatically creates directories as a part of the default targets as it was causing confusion in Discord
- Does not `#define Agon` when building on Windows or *nix. Users were having to comment it out
- Rename the resulting binary from `project` to `asm` and `asm.exe`

I've tested building `all` and `release` on Windows with VC++ 2022 in the path and on Ubuntu.

There are numerous warnings in Windows, they look valid but I did not make changes to fix them. One example is the unused parameters in

```c
UINT8 mos_save(char *filename, UINT24 address, UINT24 nbytes)
{
    return 0;
}
```

I recompiled for release on Windows and Linux and replaced the binaries in the `bin` folder.

### CODE REVIEW

**Comment by rprouse** [comment]
If desired, I can also add another PR to build all PRs and merges automatically using GitHub actions.

**Comment by snakebyte69** [comment]
I used make under Windows, much easier

**Comment by rprouse** [comment]
@snakebyte69 his does use make under Windows. Did you compile using Cygwin and gcc on Windows?

**Comment by envenomator** [comment]
Guys, while it is great you are building this on other platforms than Agon, please consider that my original goal was to write an assembler for Agon itself. Because testing quickly becomes tedious without the regular batch of unix tools, I literately hacked in a set of MOS-'compliant' file functions, that hide the differences in file/eof handling to Agon and allows me to build and test new code under Linux. Agon is the main target and that likely won't change.
I'm hesitant to change my build system to allow other people to port to their favorite platforms.

**Comment by rprouse** [comment]
@envenomator it is entirely up to you. Several people in Discord expressed a desire to have the same assembler and syntax available as a cross compiler on other platforms, so I submitted this PR. As someone that maintains several projects, I know that accepting new features means that you need to support it going forward. If you don't want to do that, then please close the PR, I will fully understand and support the decision.

We all really appreciate what you've built here. Thanks.

**Comment by envenomator** [comment]
Hi Rob,
Thanks for proposing this; I understand the desire to have a working ez80 assembler with full ADL support on different platforms. I'll have a look at your proposed changes in the makefile this weekend, and see what I can adopt to make it easier to cross-compile build going forward.

**Comment by envenomator** [comment]
Hi Rob,
I've adopted most changes to the build scripts, made some additional changes for the directory setup target, and verified interaction with the ZDSII compiler for my main builds. I'll clarify cross-platform support in the README later on, hopefully this helps!

**Comment by snakebyte69** [comment]
> @snakebyte69 his does use make under Windows. Did you compile using Cygwin and gcc on Windows?

I used https://chocolatey.org and the command line, Cygwin is another POSIX option.
GCC I think, whatever the default is.

**Pull request closed without merging**
